import { FormField } from "./projectsConfig";
import { ListColumn } from "./adminConfig";

export interface SectionDefinition {
  name: string;
  fields: FormField[];
  listFields?: FormField[];
  excludeDefaultFields?: boolean;
  endpoint?: string;
  tableDataApi?: string;
  layout?: "split" | "full";
  queryParams?: Record<string, any>;
  customActions?: {
    label: string;
    linkTemplate: string;
    showIcon?: boolean;
  }[];
  listColumns?: ListColumn[];
}

export const HOME_SECTIONS: Record<string, SectionDefinition> = {
  home_hero_section: {
    name: "Home Hero Section",
    layout: "full",
    endpoint: "/admin/home-banner",
    fields: [
      {
        name: "title.sub_heading",
        label: "Sub Heading",
        placeholder: "About K.sons",
        type: "text",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
    ],
    listFields: [
      {
        name: "desktopFile",
        label: "Desktop File",
        type: "video",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "mobileFile",
        label: "Mobile File",
        type: "video",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
    ],
    listColumns: [
      {
        key: "desktopFile",
        title: "Desktop Video",
        dataKey: "files.desktopFile",
        type: "video",
      },

      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
  home_services: {
    name: "Home Services",
    layout: "split",
    endpoint: "/admin/services",
    fields: [
      {
        name: "title.sub_heading",
        label: "Sub Heading",
        placeholder: "About K.sons",
        type: "text",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
    ],
    listFields: [
      {
        name: "title",
        label: "Title",
        placeholder: "NBFC",
        type: "text",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "description",
        label: "Description",
        placeholder: "NBFC description",
        type: "text",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "mainLabel",
        label: "Image Watermark",
        type: "text",
        section: "Media",
        colSpan: "w-full",
      },
      {
        name: "desktop_file",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "mobile_file",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-full",
      },
    ],
    listColumns: [
      {
        key: "Image",
        title: "Desktop Image",
        dataKey: "files.desktop_file",
        type: "image",
      },

      {
        key: "title",
        title: "Title",
        dataKey: "title",
      },

      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
  home_about_us: {
    name: "About Us",
    fields: [
      {
        name: "title.sub_heading",
        label: "Sub Heading",
        placeholder: "About K.sons",
        type: "text",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.small",
        label: "Small Text",
        placeholder: "Enter Small Text E.g 30",
        type: "text",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.heading",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Title",
        colSpan: "w-full",
        section: "Basic Information",
      },
      {
        name: "title.description",
        label: "Section Description",
        type: "textarea",
        placeholder: "Enter Description",
        colSpan: "w-full",
        section: "Basic Information",
      },
    ],
  },
  home_cities_section: {
    name: "Cities Section",
    layout: "full",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Our Value",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Built On Experience. Expanded With Intent",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "desktop_image",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "mobile_image",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        colSpan: "w-[48%]",
      },
    ],
  },
  home_number_and_scale: {
    name: "Number and Scale",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Numbers And Scale",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Built On Experience. Expanded With Intent",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub_heading",
        label: "Section Sub Heading",
        type: "text",
        placeholder: "Legacy & Footprint",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "title.description",
        label: "Section Description",
        type: "textarea",
        placeholder: "Enter Heading",
        section: "Basic Information",
      },
      {
        name: "list",
        label: "Numbers And Scale List",
        type: "repeater",
        addButtonText: "Add List",

        section: "Listing",
        colSpan: "w-full",
        repeaterFields: [
          {
            name: "number",
            label: "Scale Number",
            type: "text",
            placeholder: "30",
            colSpan: "w-[48%]",
          },
          {
            name: "text",
            label: "Scale Value",
            type: "text",
            placeholder: "Years Of Experience",
            colSpan: "w-[48%]",
          },
        ],
      },
    ],
  },
  home_our_value: {
    name: "Our Value",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Our Value",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Built On Experience. Expanded With Intent",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "list",
        label: "Our Value List",
        type: "repeater",
        addButtonText: "Add List",
        section: "Listing",
        colSpan: "w-full",
        repeaterFields: [
          {
            name: "title",
            label: "Title",
            type: "text",
            placeholder: "Earned through every action",
            colSpan: "w-full",
          },
          {
            name: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Enter Description",
            colSpan: "w-full",
          },
        ],
      },
    ],
  },
  home_testimonial: {
    name: "Testimonial",
    endpoint: "/admin/testimonial",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Testimonial",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Built On Experience. Expanded With Intent",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
  },
  home_csr: {
    name: "CSR & Sustainbility",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "CSR & Sustainbility",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Built On Experience. Expanded With Intent",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "title.description",
        label: "Section Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
  },
  home_our_blogs: {
    name: "Our Blogs",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Our Blogs",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Built On Experience. Expanded With Intent",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
  },
  home_news_letter: {
    name: "News Letter",
    fields: [
      {
        name: "title.main",
        label: "Newsletter",
        type: "text",
        placeholder: "News Letter",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Subscribe To Our Newsletter",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "title.description",
        label: "Description",
        type: "textarea",
        placeholder: "Be the first to receive updates, tips, and more",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
  },
  footer_description: {
    name: "Footer Description",
    fields: [
      {
        name: "title.description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
        required: true,
      },
    ],
  },
};

export const ABOUT_SECTIONS: Record<string, SectionDefinition> = {
  about_brand_metrics: {
    name: "About Brand Metrics",
    endpoint: "/admin/brand-metrics",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "list",
        label: "Metric Groups",
        type: "repeater",
        addButtonText: "Add Metric Group",
        maxItems: 2,
        minItems: 2,
        section: "Metrics",
        colSpan: "w-full",
        repeaterFields: [
          {
            name: "title",
            label: "Group Title",
            type: "text",
            placeholder: ["Execution At Scale", "Growth in Motion"],
            required: true,
            colSpan: "w-full",
          },
          {
            name: "items",
            label: "Metrics",
            type: "repeater",
            addButtonText: "Add Metrics Lists",
            colSpan: "w-full",
            repeaterFields: [
              {
                name: "number",
                label: "Metric Value",
                type: "text",
                placeholder: "8",
                colSpan: "w-[48%]",
              },
              {
                name: "text",
                label: "Metric Name",
                type: "text",
                placeholder: "Completed Projects",
                colSpan: "w-[48%]",
              },
            ],
          },
        ],
      },
    ],
  },
  our_vison_and_mission: {
    name: "Our Vision and Mission",
    excludeDefaultFields: true,
    fields: [
      {
        colSpan: "w-full",
        name: "title[0][heading]",
        label: "Vision Heading",
        type: "text",
        section: "Basic Information",
        required: true,
      },
      {
        name: "title[0][description]",
        label: "Vision Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "title[1][heading]",
        label: "Mission Heading",
        type: "text",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "title[1][description]",
        label: "Mission Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "desktop_image",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "mobile_image",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        colSpan: "w-full",
      },
    ],
  },
  about_leadership: {
    name: "About Leadership",
    endpoint: "/admin/leadership",
    layout: "full",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        placeholder: "Enter Name",
        colSpan: "w-[48%]",
      },
      {
        name: "designation",
        label: "Designation",
        type: "text",
        placeholder: "Enter Designation",
        colSpan: "w-[48%]",
      },
      {
        name: "description",
        label: "Description",
        type: "text",
        placeholder: "Enter Description",
        colSpan: "w-[48%]",
      },
      {
        name: "alt",
        label: "Alt Text",
        type: "text",
        placeholder: "Enter Alt Text",
        colSpan: "w-[48%]",
      },
      {
        name: "image",
        label: "Leader member image",
        type: "image",
        section: "Image",
        required: true,
        colSpan: "w-full",
      },
    ],
    listColumns: [
      { key: "name", title: "Name", dataKey: "name" },
      { key: "designation", title: "Designation", dataKey: "designation" },
      {
        key: "image",
        title: "Image",
        dataKey: "files.image",
        type: "image",
      },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
  about_our_value: {
    name: "About Our Values",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "list",
        label: "Values List",
        type: "repeater",
        addButtonText: "Add Value",
        section: "Basic Information",
        repeaterFields: [
          {
            name: "heading",
            label: "Heading",
            type: "text",
            placeholder: "Enter Heading",
            colSpan: "w-full",
          },
          {
            name: "description",
            label: "Description",
            type: "textarea",
            placeholder: "Enter Description",
            colSpan: "w-full",
          },
        ],
      },
      {
        name: "desktop_image",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-full",
      },
    ],
  },
  our_timeline: {
    name: "Our Timeline",
    endpoint: "/admin/timeline",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "duration",
        label: "Duration",
        type: "text",
        placeholder: ["2010 - 2025", "15 Years"],
        required: true,
        colSpan: "w-[20%]",
        section: "Timeline",
      },
      {
        name: "title",
        label: "Group Title",
        type: "text",
        placeholder: ["Company Journey", "Growth Milestones"],
        required: true,
        colSpan: "w-[25%]",
        section: "Timeline",
      },
      {
        name: "sub_title",
        label: "Group Sub Title",
        type: "text",
        placeholder: [
          "Key achievements over the years",
          "Major milestones and accomplishments",
        ],
        required: true,
        colSpan: "w-[50%]",
        section: "Timeline",
      },
      {
        name: "list",
        label: "Timeline Groups",
        type: "repeater",
        section: "Timeline",
        colSpan: "w-full",
        repeaterFields: [
          {
            name: "year",
            label: "Year",
            type: "text",
            placeholder: "2010",
            colSpan: "w-[20%]",
          },
          {
            name: "title",
            label: "Description",
            type: "text",
            placeholder: "Company founded and first office opened",
            colSpan: "w-[75%]",
          },
        ],
      },
    ],
    listColumns: [
      { key: "duration", title: "Duration", dataKey: "duration" },
      { key: "title", title: "Title", dataKey: "title" },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
};

export const CONTACT_SECTIONS: Record<string, SectionDefinition> = {
  contact_main_details: {
    name: "Contact Main Details",
    fields: [
      {
        name: "title.phone",
        label: "Phone Number",
        type: "phone",
        section: "Contact Form",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.email",
        label: "Email Address",
        type: "text",
        section: "Contact Form",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.address",
        label: "Address",
        type: "textarea",
        section: "Contact Form",
        colSpan: "w-full",
        required: true,
      },
    ],
  },
  contact_from_header: {
    name: "Contact Form Header",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
  },
};

export const CSR_SECTIONS: Record<string, SectionDefinition> = {
  csr_overview: {
    name: "CSR Overview",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "title.description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
  },
  csr_events: {
    name: "CSR and Events",
    endpoint: "/admin/events",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "title.description",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        placeholder: "Enter Title",
        required: true,
        section: "Basic Information",
        colSpan: "w-[68%]",
      },

      {
        name: "year",
        label: "Year",
        type: "text",
        section: "Basic Information",
        colSpan: "w-[28%]",
      },

      {
        name: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "mainLabel",
        label: "Image Watermark",
        type: "text",
        section: "Watermark",
        colSpan: "w-full",
      },
      {
        name: "desktop_file",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-[100%]",
      },
      {
        name: "mobile_file",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-[100%]",
      },
    ],
    listColumns: [
      { key: "title", title: "Title", dataKey: "title" },
      { key: "year", title: "Year", dataKey: "year" },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
  csr_gallery: {
    name: "CSR Gallery",
    endpoint: "/admin/events-gallery",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "eventId",
        label: "Select Event",
        type: "select",
        placeholder: "Select Event",
        section: "Basic Information",
        colSpan: "w-[100%]",
        dynamicSource: "events",
        excludeFromTable: true,
      },
      {
        name: "mainLabel",
        label: "Image Watermark",
        type: "text",
        section: "Watermark",
        colSpan: "w-full",
      },
      {
        name: "desktop_file",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "mobile_file",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        colSpan: "w-full",
      },
      {
        name: "alt",
        label: "Alt Text",
        type: "text",
        placeholder: "Enter Alt Text",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listColumns: [
      { key: "event_name", title: "Event Name", dataKey: "event.title" },
      {
        key: "image",
        title: "Image",
        dataKey: "files.desktop_file",
        type: "image",
      },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
};

export const GALLERY_SECTIONS: Record<string, SectionDefinition> = {
  gallery_our_culture: {
    name: "Our Culture",
    endpoint: "/admin/gallery",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listFields: [
      {
        name: "alt",
        label: "Alt text",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "type",
        type: "select",
        label: "Type",
        placeholder: "Select Type",
        section: "Basic Information",
        defaultValue: "image",
        required: true,
        colSpan: "w-full",
        options: [
          { value: "image", label: "Image" },
          { value: "video", label: "Video" },
        ],
      },
      {
        name: "desktop_file",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        required: true,
        colSpan: "w-full",
        showIf: (formValues: any) => formValues.type === "image",
      },
      {
        name: "mobile_file",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        colSpan: "w-full",
        showIf: (formValues: any) => formValues.type === "image",
      },
      {
        name: "desktop_file",
        label: "Desktop Video",
        type: "video",
        section: "Media",
        required: true,
        colSpan: "w-full",
        showIf: (formValues: any) => formValues.type === "video",
      },
      {
        name: "mobile_file",
        label: "Mobile Video",
        type: "video",
        section: "Media",
        colSpan: "w-full",
        showIf: (formValues: any) => formValues.type === "video",
      },
    ],
    listColumns: [
      { key: "type", title: "Type", dataKey: "type" },
      { key: "desktop_file", title: "Image", dataKey: "files.desktop_file" },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
  gallery_project_images: {
    name: "Project Images Section",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
  },
};

export const NRI_CORNOR_SECTIONS: Record<string, SectionDefinition> = {
  "nri-cornor": {
    name: "NRI Cornor",
    endpoint: "/admin/other-faqs",
    queryParams: { faq_type: "nri-corner" },
    tableDataApi: "/admin/other-faqs",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Faqs Sub Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "faq_type",
        label: "",
        type: "hidden",
        defaultValue: "nri-corner",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "status",
        label: "",
        type: "hidden",
        defaultValue: true,
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "question",
        label: "Question",
        type: "text",
        placeholder: "Enter Question",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "answer",
        label: "Answer",
        type: "textarea",
        placeholder: "Enter Answer",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listColumns: [
      { key: "question", title: "Question", dataKey: "question" },
      { key: "answer", title: "Answer", dataKey: "answer" },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "sequence", title: "Sequence", dataKey: "seq" },
    ],
  },
};

export const TESTIMONIALS_SECTIONS: Record<string, SectionDefinition> = {
  testimonials: {
    name: "Testimonials",
    endpoint: "/admin/testimonials",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Faqs Sub Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
  },
};

export const EMI_CALCULATOR_SECTIONS: Record<string, SectionDefinition> = {
  "emi-calculator": {
    name: "Emi Calculator",
    endpoint: "/admin/emi-calculator",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Faqs Sub Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
  },
};

export const BLOG_SECTIONS: Record<string, SectionDefinition> = {
  blog_overview: {
    name: "Blog Overview",
    endpoint: "/admin/blogs",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Enter Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        placeholder: "Enter Title",
        required: true,
        section: "Basic Information",
        colSpan: "w-[68%]",
      },
      {
        name: "dateAt",
        label: "Date",
        type: "date",
        section: "Basic Information",
        colSpan: "w-[28%]",
      },
      {
        name: "description.short",
        label: "Short Description",
        type: "textarea",
        placeholder: "Enter Short Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "description.main",
        label: "Blog Description",
        type: "textEditor",
        placeholder: "Enter Blog Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "description.conclusion",
        label: "",
        type: "textarea",
        placeholder:
          "Choosing a K.sons township in Mathura is more than purchasing property—it’s securing a lifestyle, community, and investment all at once.",
        section: "Conclusion",
        colSpan: "w-full",
      },
      {
        name: "alt",
        label: "Alt Text",
        type: "text",
        placeholder: "Enter Alt Text",
        section: "SEO Settings",
        colSpan: "w-full",
      },
      {
        name: "seoTags.meta_title",
        label: "Meta Title",
        type: "text",
        section: "SEO Settings",
      },
      {
        name: "seoTags.meta_keywords",
        label: "Meta Keywords",
        type: "textarea",
        section: "SEO Settings",
      },
      {
        name: "seoTags.meta_description",
        label: "Meta Description",
        type: "textarea",
        section: "SEO Settings",
      },
      {
        type: "textarea",
        name: "seoTags.headData",
        label: "Head Data",
        section: "SEO Section",
      },
      {
        type: "textarea",
        name: "seoTags.bodyData",
        label: "Body Data",
        section: "SEO Section",
      },
      {
        name: "mainLabel",
        type: "text",
        label: "Watermark",
        section: "Media",
      },
      // Files ========== //
      {
        name: "desktop_image",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        // required: true,
        colSpan: "w-full",
      },
      {
        name: "mobile_image",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        // required: true,
        colSpan: "w-full",
      },
    ],
    listColumns: [
      { key: "title.main", title: "Title", dataKey: "title" },
      { key: "is_popular", title: "Popular Blog", dataKey: "isPopular" },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "seq", title: "Sequence", dataKey: "seq" },
    ],
    // customActions: [
    //   {
    //     label: "Add FAQs",
    //     linkTemplate: "/admin/faq/blog/{id}?title={title}",
    //     showIcon: true,
    //   },
    // ],
  },
};

export const FAQ_SECTIONS: Record<string, SectionDefinition> = {
  faq: {
    name: "FAQ",
    endpoint: "/admin/faqs",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Faqs Sub Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "status",
        label: "",
        type: "hidden",
        defaultValue: true,
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "question",
        label: "Question",
        type: "text",
        placeholder: "Enter Question",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "answer",
        label: "Answer",
        type: "textarea",
        placeholder: "Enter Answer",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listColumns: [
      { key: "question", title: "Question", dataKey: "question" },
      { key: "seq", title: "Sequence", dataKey: "seq" },
    ],
  },
};

export const HOME_LOAN_SECTIONS: Record<string, SectionDefinition> = {
  "home-loan": {
    name: "Home Loan",
    // endpoint: "/admin/home-loan",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "title.short",
        label: "Short Description",
        type: "textarea",
        placeholder: "Enter Short Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "title.description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
  },
};

export const TAX_BENEFITS_SECTIONS: Record<string, SectionDefinition> = {
  "tax-benefits": {
    name: "Tax Benefits",
    endpoint: "/admin/other-faqs",
    queryParams: { faq_type: "tax-benefits" },
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Faqs Sub Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listFields: [
      {
        name: "faq_type",
        label: "",
        type: "hidden",
        defaultValue: "tax-benefits",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "status",
        label: "",
        type: "hidden",
        defaultValue: true,
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "question",
        label: "Question",
        type: "text",
        placeholder: "Enter Question",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "answer",
        label: "Answer",
        type: "textarea",
        placeholder: "Enter Answer",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listColumns: [
      { key: "question", title: "Question", dataKey: "question" },
      { key: "answer", title: "Answer", dataKey: "answer" },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "seq", title: "Sequence", dataKey: "seq" },
    ],
  },
};

export const NEWS_EVENTS_SECTIONS: Record<string, SectionDefinition> = {
  "news-events": {
    name: "News & Events",
    endpoint: "/admin/news",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-[48%]",
      },
      {
        name: "title.sub",
        label: "Section Heading",
        type: "text",
        placeholder: "Faqs Sub Heading",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "title.description",
        label: "Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listFields: [
      {
        name: "news_mode",
        label: "News Type",
        type: "select",
        options: [
          { value: "online", label: "Online" },
          { value: "offline", label: "Offline" },
        ],
        defaultValue: "online",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "dateAt",
        label: "Date",
        type: "date",
        placeholder: "Enter Date",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "title",
        label: "Title",
        type: "text",
        placeholder: "Enter Title",
        section: "Basic Information",
        colSpan: "w-full",
      },

      // {
      //   name: "publish_by",
      //   label: "Published By",
      //   type: "text",
      //   placeholder: "Enter Published By",
      //   section: "Basic Information",
      //   colSpan: "w-full",
      //   showIf: (formValues: any) => formValues.news_mode === "Online",
      // },

      {
        name: "newsLink",
        label: "News Link",
        type: "text",
        placeholder: "Enter News Link",
        section: "Basic Information",
        colSpan: "w-full",
        showIf: (formValues: any) => formValues.news_mode === "online",
      },
      {
        name: "description.short",
        label: "Description",
        type: "textarea",
        placeholder: "Enter Description",
        section: "Basic Information",
        colSpan: "w-full",
        showIf: (formValues: any) => formValues.news_mode === "online",
      },

      // files
      {
        name: "desktop_file",
        label: "Desktop Image",
        type: "image",
        section: "Media",
        colSpan: "w-[100%]",
        showIf: (formValues: any) => formValues.news_mode === "offline",
      },
      {
        name: "mobile_file",
        label: "Mobile Image",
        type: "image",
        section: "Media",
        colSpan: "w-[100%]",
        showIf: (formValues: any) => formValues.news_mode === "offline",
      },
    ],
    listColumns: [
      { key: "title", title: "Title", dataKey: "title" },
      { key: "news_mode", title: "News Type", dataKey: "news_mode" },
      { key: "dateAt", title: "Date", dataKey: "dateAt" },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "seq", title: "Sequence", dataKey: "seq" },
    ],
  },
};

export const INVESTOR_SECTIONS: Record<string, SectionDefinition> = {
  investor: {
    name: "Investor",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "title.description",
        label: "Section Description",
        type: "textarea",
        placeholder: "Enter Section Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "title.mainLabel",
        label: "Watermark",
        type: "text",
        placeholder: "Enter Watermark",
        section: "Media",
        colSpan: "w-full",
      },
      {
        name: "desktop_file",
        label: "Image",
        type: "image",
        placeholder: "Enter File",
        section: "Media",
        colSpan: "w-full",
      },
    ],
  },
};
export const CAREER_SECTIONS: Record<string, SectionDefinition> = {
  life_at_ksons: {
    name: "Life At K-Sons",
    endpoint: "/admin/life-at-ksons",
    layout: "full",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "description.long",
        label: "Section Description",
        type: "textarea",
        placeholder: "Enter Section Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listFields: [
      {
        name: "alt",
        label: "Alt Text",
        type: "text",
        placeholder: "Enter Alt Text",
        section: "Basic Information",
        colSpan: "w-[100%]",
      },
      {
        name: "desktop_file",
        label: "Desktop Image",
        type: "image",
        section: "Basic Information",
        colSpan: "w-[48%]",
        required: true,
      },
      {
        name: "mobile_file",
        label: "Mobile Image",
        type: "image",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
    ],
    listColumns: [
      { key: "alt", title: "Alt Text", dataKey: "alt" },
      {
        key: "desktop_file",
        title: "Desktop Image",
        dataKey: "files.desktop_file",
      },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "seq", title: "Sequence", dataKey: "seq" },
    ],
  },
  career_now_hiring: {
    name: "Now Hiring",
    endpoint: "/admin/jobs",
    layout: "full",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "description.long",
        label: "Section Description",
        type: "textarea",
        placeholder: "Enter Section Description",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
    listFields: [
      {
        name: "title",
        label: "Job Title",
        type: "text",
        placeholder: "Enter Job Title",
        section: "Basic Information",
        colSpan: "w-[100%]",
      },
      {
        name: "location",
        label: "Job Location",
        type: "text",
        placeholder: "Enter Job Location",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "experience_required",
        label: "Experience Required",
        type: "text",
        placeholder: "3+ Years",
        section: "Basic Information",
        colSpan: "w-[48%]",
      },
      {
        name: "status",
        label: "",
        type: "hidden",
        defaultValue: true,
        section: "Basic Information",
        colSpan: "w-full",
      },
      {
        name: "skills",
        label: "Skills",
        type: "repeater",
        isFlatArray: true,
        section: "Basic Information",
        colSpan: "w-[48%]",
        addButtonText: "Add Skills",
        repeaterFields: [
          {
            name: "skill",
            label: "",
            type: "text",
            placeholder: "Enter Skill",
            colSpan: "w-full",
          },
        ],
      },
    ],
    listColumns: [
      { key: "title", title: "Job Title", dataKey: "title" },
      { key: "location", title: "Location", dataKey: "location" },
      {
        key: "experience_required",
        title: "Experience",
        dataKey: "experience_required",
      },
      { key: "status", title: "Status", dataKey: "status" },
      { key: "seq", title: "Sequence", dataKey: "seq" },
    ],
  },
  career_form_section: {
    name: "Career Form Section",
    fields: [
      {
        name: "title.main",
        label: "Section Title",
        type: "text",
        placeholder: "Faqs Heading",
        section: "Basic Information",
        required: true,
        colSpan: "w-full",
      },
      {
        name: "title.sub",
        label: "Section Subtitle",
        type: "text",
        placeholder: "Enter Section Subtitle",
        section: "Basic Information",
        colSpan: "w-full",
      },
    ],
  },
};
